@startuml

entity HraciaPlocha as HP
entity Policko as P
entity VychodiskovePostavenie as VP
entity Kamen as K
actor Hrac as H
entity Tah as T
entity Skok as S
actor Rozhodca as R

HP "1" -- "64" P : ma >
P -- "0..1" K : obsahuje >
K -- "0..1" P : lezi na >
VP -- "0..*" K : je tvorene z >
K -- "0..*" K : preskakuje >
H "1..*" - "0..*" K : pouziva >
H -- T : vykonava >
T "1" -- "1..3" S : pozostava >
R "0..1" - "0..*" S : kontroluje >

@enduml