@startuml

skinparam packageStyle rectangle
skinparam ClassAttributeIconSize 0

package Symetria as S {
    class +Hrac
    class +Skore 
    class +Symetria 
    class +Zapas
}

package Hra as H {
    class //+Hra// 
    class +HraciaPlocha
    class +Kamen
    class +Policko
    class +Pravidlo 
    class +Tah
}

package SkokovaHra as SH {
    class +SkokovaHra
}

package Hadivka as HA {
    class +Hadivka
}

package Pravidla as P {
    class +Pravidlo
    class +PravidloPoctuSkokov
    class +PravidloDlhehoSkoku
    class +PravidloKratkehoSkoku
}

S ..> H 
H ..> P 
SH ..> P
HA ..> P

@enduml